### ISSUE TITLE
MSFS/Simconnect has not been started

### ISSUE THREAD

**Issue by soundy83** [hawkeye-stan/msfs-popout-panel-manager#19]
I go into the sim and number my panels but I am getting an error when I hit 'Start Pop Out' which states that MSFS/Simconnect has not been started.

Is simconnect an external piece of software?

Cheers.

**Comment by hawkeye-stan** [comment]
It just means somehow the app has lost connection to the game or the game hasn't been stared. Try restarting Pop Out manager to see if pop out works. When the app is connected to MSFS using SimConnect (MSFS built-in connection API), you should see the connection icon lights up in green in the upper right corner of the app.

![Screenshot 2022-06-10 092000](https://user-images.githubusercontent.com/72271266/173073358-7a610497-e9c2-46ec-a7ed-48a676a1bf48.png)
.

**Comment by soundy83** [comment]
Ok interesting, I have never been able to get that to go green, restarted multiple times, even different installs, it isnt working. could it be due to using xbox PC pass?

**Comment by soundy83** [comment]
022-06-11 06:50:51,712 [1] ERROR MSFSPopoutPanelManager.WpfApp.App - Could not load file or assembly 'Microsoft.FlightSimulator.SimConnect, Version=11.0.62651.3, Culture=neutral, PublicKeyToken=baf445ffb3a06b5c'. An attempt was made to load a program with an incorrect format.
System.BadImageFormatException: Could not load file or assembly 'Microsoft.FlightSimulator.SimConnect, Version=11.0.62651.3, Culture=neutral, PublicKeyToken=baf445ffb3a06b5c'. An attempt was made to load a program with an incorrect format.
File name: 'Microsoft.FlightSimulator.SimConnect, Version=11.0.62651.3, Culture=neutral, PublicKeyToken=baf445ffb3a06b5c'
   at MSFSPopoutPanelManager.FsConnector.SimConnector.Stop()
   at MSFSPopoutPanelManager.Provider.SimConnectManager.Stop() in C:\Src\MSFS Pop Out Panel Manager\master\Provider\SimConnectManager.cs:line 54
   at MSFSPopoutPanelManager.WpfApp.ViewModel.ApplicationViewModel.OnExit(Object commandParameter) in C:\Src\MSFS Pop Out Panel Manager\master\WpfApp\ViewModel\ApplicationViewModel.cs:line 171
   at MSFSPopoutPanelManager.WpfApp.ViewModel.DelegateCommand.Execute(Object parameter) in C:\Src\MSFS Pop Out Panel Manager\master\WpfApp\ViewModel\DelegateCommand.cs:line 17
   at MSFSPopoutPanelManager.WpfApp.ApplicationWindow.Window_Closing(Object sender, CancelEventArgs e) in C:\Src\MSFS Pop Out Panel Manager\master\WpfApp\ApplicationWindow.xaml.cs:line 100
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at MahApps.Metro.Controls.MetroWindow.<>n__0(CancelEventArgs e)
   at MahApps.Metro.Controls.MetroWindow.OnClosing(CancelEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2022-06-11 10:42:19,210 [1] ERROR MSFSPopoutPanelManager.WpfApp.App - Could not load file or assembly 'Microsoft.FlightSimulator.SimConnect, Version=11.0.62651.3, Culture=neutral, PublicKeyToken=baf445ffb3a06b5c'. An attempt was made to load a program with an incorrect format.

**Comment by hawkeye-stan** [comment]
Hmmm, looks like there is a mismatch of Windows OS version and Pop Out Manager (64bit) or you're missing some files which caused the failure in Microsoft SimConnect.

Would you please help check the following in Pop Out Manager installation folder?

1. Confirm you're running 64bit version of Windows 10/11

Pop Out Manager only works on 64bit Windows.

2. Check to see if the following 2 files are in the installation folder:
    - Microsoft.FlightSimulator.SimConnect.dll
    - SimConnect.dll  (your error most likely is caused by missing this file)

If one or more of the above file is missing, please redownload Pop Out Manager release package and copy the files into your installation folder.

Hope this fixes your issue.

**Comment by soundy83** [comment]
Hi and thanks for the help.

I double checked and yes definately 64bit OS, and both of those files are present, I have also downloaded the files more than once. so they should be fine.

**Comment by hawkeye-stan** [comment]
I'm at a lost regarding your issue. I've tried to replicate your exact error and the only way I can do it is to remove SimConnect.dll from the installation folder. 

How Pop Out Manager (.NET app) works is it uses managed Dll 'Microsoft.FlightSimulator.SimConnect.dll' which in turns call Microsoft MSFS SDK Dll 'SimConnect.dll'. When there is bit version mismatch, which is not the case in this instance, or missing SimConnect.dll, it will show your exact error.

Another thing to try is to download MSFS SDK by enabling developers mode in General Options in the game. A toolbar will appear at the top. Go over to the 'Help' menu and download 'SDK Install (core)'. Install the SDK.  You will then find the SDK installed in the folder 'C:\SDK'. Navigation to the folder 'C:\MSFS SDK\SimConnect SDK\lib' and you should see a copy of 'SimConnect.dll'. Also go deeper to the folder 'managed' and you should see a copy of 'Microsoft.FlightSimulator.SimConnect.dll'. Copy these 2 files into Pop Out Manager and see if the app works.

If you're not able to download the SDK, currently there is a bug in MSFS that prevent the SDK from downloading, go over to this forum post and download the core SDK with the provided link. 

https://forums.flightsimulator.com/t/problems-with-sdk-download/514370

If the app still does not work, then something in your system is preventing 'SimConnect.dll' from loading.

**Comment by hawkeye-stan** [comment]
Merge with issue #21
