### ISSUE TITLE
.NET Crash

### ISSUE THREAD

**Issue by Maarp68** [hawkeye-stan/msfs-popout-panel-manager#2]
G'day again,

Just copying from the MS Forum:

Once I press analyse the pop-up manager opens at least three of those four packages and then crashes with the error message I’m showing here (ooops, can’t upload images it seems). It’s a .Net error “Unhandled Exception Error has occurred in your application…”

Interestingly I've been able to get the Popup Manager to work on the Milviz Turbo Porter with 2 panels so is it possibly the CRJ causing the problem?

Cheers

Warwick

![Screenshot (8)](https://user-images.githubusercontent.com/96105852/145950436-510432c8-a952-42fd-b8f3-19f8220651f0.png)

**Comment by hawkeye-stan** [comment]
Hi Warwick,

Hmm... have you encounter the .NET crash again and consistently getting it ? If so, would you be able to expand the "Details" drop down in the error message dialog and use you mouse to highlight all the detail exception text and copy and paste them into this issue thread. Also, what screen resolution are you using (1080p / 1440p /4K)?

I also bought the Aerosoft cr550/700 a while back but haven't flown it in the last couples weeks. I'm getting some weird behavior with this plane with SU7. First time I go into the plane, my mouse right-ALT click doesn't work, and all subsequent flights with other plane in the same game session do not work either. After I restart the game. Everything works again and attach are screenshots for one panel pop out and 4 panels. The non-zero coordinates you see are after I moved the panels into desire location and clicked "save settings".

Anyway, your error message above of "Parameter is not valid" a generic error and most likely has to do with image and window manipulation issue in my code. If I can get the detail info I will be able to pin down which line and section of my code is causing your error. I'll do more testing with CRJ550 tonight when I get off work.

Thank you for helping me out testing and using my app!

Stanley

![image1](https://user-images.githubusercontent.com/72271266/146020559-d826b24c-73d4-4109-a7e6-7e188bd51ec1.png)
![image2](https://user-images.githubusercontent.com/72271266/146020562-8be3c562-2f42-4754-b304-e46ab477a13e.png)

**Comment by Maarp68** [comment]
G'day Stanley,

Thanks so much for getting back to me. Both my monitors are running at 1920x1080.

Also I've tried the app again in the Milviz Turbo Porter and it works perfectly.

I'm loving the CRJ 550 (I'm really into the more complex aircraft). Havn't had the problems you've found but also there was an update in the last day or so that might help you.

Here is the full error text:

Many thanks

Warwick


************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.GetExpandButtonHeightRatio(IntPtr windowHandle, Bitmap sourceImage, Int32 numberOfRows, Double percentFromLeft)
   at MSFSPopoutPanelManager.PanelAnalysisModule.AnalyzeMergedPopoutWindows(IntPtr windowHandle)
   at MSFSPopoutPanelManager.PanelAnalysisModule.Analyze(WindowProcess simulatorProcess, Int32 profileId, Int32 panelsCount)
   at MSFSPopoutPanelManager.PanelManager.Analyze()
   at MSFSPopoutPanelManager.UserControlPanelSelection.buttonAnalyze_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Private.CoreLib.dll
----------------------------------------
MSFSPopoutPanelManager
    Assembly Version: 2.2.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Runtime.dll
----------------------------------------
System.Threading
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Threading.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 5.0.12.0
    Win32 Version: 5.0.1221.52310
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.12/System.Windows.Forms.Primitives.dll
----------------------------------------
DarkUI
    Assembly Version: 2.0.1.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Forms
    Assembly Version: 5.0.12.0
    Win32 Version: 5.0.1221.52310
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.12/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 5.0.0.2
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.12/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Collections.dll
----------------------------------------
System.Drawing
    Assembly Version: 5.0.12.0
    Win32 Version: 5.0.1221.52310
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.12/System.Drawing.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.1221.52310
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.12/Accessibility.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/mscorlib.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Runtime.Extensions.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.12/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.ComponentModel.dll
----------------------------------------
System.Memory
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Memory.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.12/System.Resources.Extensions.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/netstandard.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.ObjectModel.dll
----------------------------------------
System.Linq
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Linq.dll
----------------------------------------
System.Buffers
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Buffers.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Collections.Concurrent.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Runtime.Numerics.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Private.Uri.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Private.Xml.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Reflection.Emit.Lightweight.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Private.CoreLib.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Collections.NonGeneric.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Xml.XmlSerializer.dll
----------------------------------------
System.Text.Encoding.CodePages
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO.FileSystem
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.IO.FileSystem.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Text.RegularExpressions.dll
----------------------------------------
System.Reflection.Emit
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Reflection.Emit.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Private.Xml.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Threading.ThreadPool.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/Microsoft.Win32.Registry.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Diagnostics.Process.dll
----------------------------------------
AForge.Imaging
    Assembly Version: 2.2.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.Tasks.Parallel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Threading.Tasks.Parallel.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Diagnostics.Tracing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Core.dll
----------------------------------------
Gma.System.MouseKeyHook
    Assembly Version: 5.6.130.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.dll
----------------------------------------
System.Resources.ResourceManager
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Resources.ResourceManager.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.12/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

**Comment by hawkeye-stan** [comment]
Hi Warwick,

Thanks for the detail info, it really points me to the right direction. Looks like the reason for crashing is definitely when the app got stuck in an infinite loop trying to find the magnifying glass icon. And this only happens on certain combination of screen resolution and panel type since panels all have different size on different plane. Microsoft just can't code the menu bar to a standard size. LOL!

I'm currently working on version 3.0 of the app which will have a brand new method of popping out and separating the panels as suggested by another user in the forum to greatly improve accuracy. I believe the new method should fix your problem.  Also, this version will also have the long awaited cold start feature (aka. all blank screens recognition). I'm to hoping finish coding it and release the new version before Christmas so all the home cockpit builders can truly used the app "BEFORE" engine starts, hahaha!

Once again, thanks for your patience and your help to make the app better!

**Comment by ssewell** [comment]
> I'm currently working on version 3.0 of the app which will have a brand new method of popping out and separating the panels as suggested by another user in the forum to greatly improve accuracy. I believe the new method should fix your problem. Also, this version will also have the long awaited cold start feature (aka. all blank screens recognition). I'm to hoping finish coding it and release the new version before Christmas so all the home cockpit builders can truly used the app "BEFORE" engine starts, hahaha!

This sounds amazing! I can't wait to try it out and look at the code to see how you're pulling this off.

**Comment by hawkeye-stan** [comment]
Please try version 3 of the application and see if it works for you.

**Comment by Maarp68** [comment]
Version 3 works a treat. Great work, thanks so much.
