### ISSUE TITLE
app does not detect msfs2020 and errors on exit

### ISSUE THREAD

**Issue by JaimeLeon2** [hawkeye-stan/msfs-popout-panel-manager#21]
I installed latest version 3.3.3.  The program starts, but does not seem to detect that msfs2020 is active.

![image](https://user-images.githubusercontent.com/86563553/174913193-a6438630-a133-47c8-b126-3223605210a8.png)

Upon exit I get three errors like this and in the log file.

![image](https://user-images.githubusercontent.com/86563553/174913267-06cfaf47-a6af-4903-a853-0d775bf94335.png)

```
2022-06-21 18:31:34,618 [1] ERROR MSFSPopoutPanelManager.WpfApp.App - Could not load file or assembly 'Microsoft.FlightSimulator.SimConnect, Version=11.0.62651.3, Culture=neutral, PublicKeyToken=baf445ffb3a06b5c'. An attempt was made to load a program with an incorrect format.
System.BadImageFormatException: Could not load file or assembly 'Microsoft.FlightSimulator.SimConnect, Version=11.0.62651.3, Culture=neutral, PublicKeyToken=baf445ffb3a06b5c'. An attempt was made to load a program with an incorrect format.
File name: 'Microsoft.FlightSimulator.SimConnect, Version=11.0.62651.3, Culture=neutral, PublicKeyToken=baf445ffb3a06b5c'
   at MSFSPopoutPanelManager.FsConnector.SimConnector.Stop()
   at MSFSPopoutPanelManager.Provider.SimConnectManager.Stop() in C:\Src\MSFS Pop Out Panel Manager\master\Provider\SimConnectManager.cs:line 54
   at MSFSPopoutPanelManager.WpfApp.ViewModel.ApplicationViewModel.OnExit(Object commandParameter) in C:\Src\MSFS Pop Out Panel Manager\master\WpfApp\ViewModel\ApplicationViewModel.cs:line 171
   at MSFSPopoutPanelManager.WpfApp.ViewModel.DelegateCommand.Execute(Object parameter) in C:\Src\MSFS Pop Out Panel Manager\master\WpfApp\ViewModel\DelegateCommand.cs:line 17
   at MSFSPopoutPanelManager.WpfApp.ApplicationWindow.Window_Closing(Object sender, CancelEventArgs e) in C:\Src\MSFS Pop Out Panel Manager\master\WpfApp\ApplicationWindow.xaml.cs:line 100
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at MahApps.Metro.Controls.MetroWindow.<>n__0(CancelEventArgs e)
   at MahApps.Metro.Controls.MetroWindow.OnClosing(CancelEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2022-06-21 18:32:08,006 [1] ERROR MSFSPopoutPanelManager.WpfApp.App - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MSFSPopoutPanelManager.WpfApp.App.ShowExceptionDialog() in C:\Src\MSFS Pop Out Panel Manager\master\WpfApp\App.xaml.cs:line 81
   at MSFSPopoutPanelManager.WpfApp.App.HandleDispatcherException(Object sender, DispatcherUnhandledExceptionEventArgs e) in C:\Src\MSFS Pop Out Panel Manager\master\WpfApp\App.xaml.cs:line 63
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2022-06-21 18:32:08,959 [1] ERROR MSFSPopoutPanelManager.WpfApp.App - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MSFSPopoutPanelManager.WpfApp.App.ShowExceptionDialog() in C:\Src\MSFS Pop Out Panel Manager\master\WpfApp\App.xaml.cs:line 81
   at MSFSPopoutPanelManager.WpfApp.App.HandleDispatcherException(Object sender, DispatcherUnhandledExceptionEventArgs e) in C:\Src\MSFS Pop Out Panel Manager\master\WpfApp\App.xaml.cs:line 63
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at MSFSPopoutPanelManager.WpfApp.App.Main()
```

This is a fresh install of Windows 10 21H2 with all updates and MSFS2020.
I hope this can help to resolve this issue.

**Comment by hawkeye-stan** [comment]
Hi,

I'm merging your issue with issue #19. Looks like you're the second user getting the exact same issue (SimConnect failed to load) on Windows 10 which I'm not able to replicate on my PC. Would you please try the possible solutions suggested in issue #19? I'll see what I can do on my end such as building a windows 10 PC or virtual machine and try to figure out what is causing the problem. Unfortunately, I haven't heard back from the other user did my suggested solution solve his issue.

**Comment by JaimeLeon2** [comment]
OK. I will try tomorrow and report back the results. I did have this app running well for about 6 months before. This unwanted behavior is happening after the fresh install of Windows 10 21h2.
I did have to uninstall one of the latest windows updates because it broke the wifi mobile Hotspot function, which I use to convert an android tablet into a windows monitor. I doubt this would be related, but I mention it in case it does have any relevance.

**Comment by hawkeye-stan** [comment]
Hi Jaime,

I doubt uninstalling windows update is the cause of the problem. As you're mentioning MobiFlight, I went to check what platform MobiFlight is built against, and it is built for x86 (32bit) instead of x64 (64bit). It also uses 32bit version of SimConnect.dll even though their source code also include 64bit version of SimConnect.dll but is not being used.

So this gave me an idea. I've repackaged Pop Up Manager to target "AnyCPU" + "x86 only" (32bit) instead of "x64" (64bit) and I've put copy of zip packages [msfs-popout-panel-manager-anycpu-test.zip](https://github.com/hawkeye-stan/msfs-popout-panel-manager/releases/download/v3.3.3-test/msfs-popout-panel-manager-anycpu-test.zip) and [msfs-popout-panel-manager-x86-test.zip](https://github.com/hawkeye-stan/msfs-popout-panel-manager/releases/download/v3.3.3-test/msfs-popout-panel-manager-x86-test.zip) for you to test.

Would you mind helping me run couple of quick tests to see if one of these versions fix your problem? 

1. Please download "AnyCPU" package first and unzip it to a different folder. 

2. Start MSFS and wait for the main menu to appear, this guarantee SimConnect has been started on MSFS side.

3. Run MSFSPopoutPanelManager.exe

4. After a few seconds, you should see the connection icon turns green in the upper right corner.

5. If it does not, please exit Pop Out Manager, you will then see the same 3 error pop ups you reported before and the error.log will have the same error messages about unable to load file and BadImageFormatException.  Please continue to Step 6. If it does connect, problem solve and please report back!

6. Download x86 (32bit) package and unzip it to a different folder. 

7. Your MSFS should have started from Step 2, if not, start MSFS.

8. Run MSFSPopoutPanelManager.exe.

9. After a few seconds, you should see the connection icon turns green in the upper right corner.

10. If it does not, when you exit Pop Out Manager, you will see some error messages. Please check error.log and report back with the error message. If it does connect, problem solve and please report back also.

If "AnyCPU" version does work, then it is truly a mystery to me since it is essentially the same as targeting x64 platform on most Windows PC. If the "x86" version works, then it is even a bigger mystery since Pop Out Manager has been packaged as 64bit app for months and suddenly it stops working on certain PC with the same SimConnect DLL. Either way, it will help me identify the root cause and gives me a path forward and decide if Pop Out Manager needs to downgrade to 32bit app to support all users.

Thank you in advance for your help in testing.

Stanley

**Comment by JaimeLeon2** [comment]
Hello,
TEST 1 with anyCPU had exactly the same result no connection and the three errors upon exit.

TEST 2 with x86.
I had to install .net for x86 but the app started OK and connected to Simconnect
![image](https://user-images.githubusercontent.com/86563553/175076344-62d63d24-7491-4c7d-bc81-ef3bf2e4de0e.png)

No errors on exit. Yaaaay!

Thank you for taking the time to solve my issue.

**Comment by hawkeye-stan** [comment]
Awesome! 

Your test tells me that 64it version of SimConnect is somehow broken and I will need to figure out why. Also I will need some time to figure out how to split the app into 2 versions (32 and 64bit) if I cannot come up with a permanent solution.

Also, I will be doing another feature/bug fix release this week (Version 3.3.4), please do not use AutoUpdate when prompt to upgrade your working app. Just choose "skip this version" and I'll create an x86 build for you to download so you can also enjoy  the bug fixes and new feature.

Thank you for your help and support!

**Comment by hawkeye-stan** [comment]
OK.... the solution cannot be this easy! I can reproduce your issue with a clean Windows 10 21H2 virtual machine using Hyper-V. And after I install the following framework "Microsoft Visual C++ 2015-2022 Redistributable (x64) 14.32.31326", the error no longer appears. I didn't exactly test the actual connection since I'm using a remote PC but the error goes away nevertheless.  

https://aka.ms/vs/17/release/vc_redist.x64.exe

I found an article post yesterday on another unrelated MSFS tool that is experiencing your issue similar to yours.  I was suspecting the x64 version of SimConnect.dll needs a Visual C++ library which is installed in most computer (after many games/programs installation). I was not able to reproduce it on my PC even after uninstalling the above library. But on a clean PC, this library does not exist the error appears 100% of the time. So please try to install the above VC++ library and redownload the regular version 3.3.3 of Pop Out Manager and unzip to a test folder. Run MSFS and see if you can connect. If so, then the problem is truly solved.

Stanley

**Comment by JaimeLeon2** [comment]
Hello Stanley,
This is to report that after installing the C++ Redistributable package and reinstalling the regular msfs-popout-manager v3.3.3, everything is working normally.  So, congrats, it seems you have figured out what was wrong.  Thank you so much.
