### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by dustin141** [hawkeye-stan/msfs-popout-panel-manager#4]
Hi, I am getting this error on start and not sure what to do. Any ideas?

![image](https://user-images.githubusercontent.com/96915860/147827007-43b9cd44-444b-42b3-b5b5-32d4df6a2185.png)

2021-12-31 08:57:12,993 [1] ERROR MSFSPopoutPanelManager.Program - There is an error in XML document (3, 2).
System.InvalidOperationException: There is an error in XML document (3, 2).
 ---> System.Xml.XmlException: There are multiple root elements. Line 3, position 2.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.ReadEndElement()
   at System.Xml.Serialization.XmlSerializationReader.ReadEndElement()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSimBaseDocument.Read3_SimBaseDocument(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSimBaseDocument.Read4_SimBaseDocument()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at MSFSPopoutPanelManager.Shared.Autostart.CheckIsAutoStart() in C:\Src\msfs-popout-panel-manager\Shared\Autostart.cs:line 122
   at MSFSPopoutPanelManager.UIController.StartUpController.Initialize() in C:\Src\msfs-popout-panel-manager\UIController\StartUpController.cs:line 37
   at MSFSPopoutPanelManager.UI.StartupForm..ctor() in C:\Src\msfs-popout-panel-manager\UI\StartupForm.cs:line 40
   at MSFSPopoutPanelManager.Program.Main() in C:\Src\msfs-popout-panel-manager\Program.cs:line 38
[error.log](https://github.com/hawkeye-stan/msfs-popout-panel-manager/files/7796358/error.log)

**Comment by hawkeye-stan** [comment]
Hi Dustin,

Please see the closed issue [#3](https://github.com/hawkeye-stan/msfs-popout-panel-manager/issues/3) to see if you have a similar issue in your 3rd party app autostart file "exe.xml" is valid:

Here is the instruction from my forum post to help you find where exe.xml file is located on your machine:
----------------------------------------------------------------------------------------------------
My app is trying to read the default MSFS 3rd party app autostart file EXE.XML in your MSFS LocalCache folder and it is encountering something that is unexpected, most likely an invalid XML file.

For a quick fix, please edit exe.xml file directly. First make a backup copy of the file in case something goes wrong.

You can find the file in the following folder for MS store version of the game.
%LocalAppData%\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\

For steam version of the game:
%AppData%\Microsoft Flight Simulator\LocalCache\

Once you open the file in notepad, you should see one of more for all the plugins/apps that you loaded at startup. Please copy the content of the file and paste in  XML validator from the following link. It should tell you where the error is and you can correct the error, save the file and everything should work.

[XML Validator](https://codebeautify.org/xmlvalidator)
----------------------------------------------------------------------------------------

It you need further help, please attach the "exe.xml" file, you've to rename it to exe.txt or zip it up for github. I'll be glad to help you diagnose and fix the file. 

Stanley
